# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

dist: focal

language: php

php:
  - 7.4
  - 8.0
  - 8.1

before_install:
  - composer update --dev

script:
  - cd test && ../vendor/bin/run_unit_tests
